# Generated by Django 5.0.2 on 2025-06-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno interpreta')),
                ('bio', models.TextField(blank=True, verbose_name='Biografie')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Země původu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Interpret',
                'verbose_name_plural': 'Interpreti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název alba')),
                ('release_date', models.DateField(verbose_name='Datum vydání')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Obal alba')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='Interpret')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Alba',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název skladby')),
                ('duration', models.DurationField(verbose_name='Délka skladby')),
                ('track_number', models.PositiveIntegerField(verbose_name='Číslo skladby')),
                ('lyrics', models.TextField(blank=True, verbose_name='Text písně')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Skladba',
                'verbose_name_plural': 'Skladby',
                'ordering': ['track_number'],
            },
        ),
    ]
