# Generated by Django 5.2.1 on 2025-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Zpráva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Odesláno')),
            ],
            options={
                'verbose_name': 'Zpráva z formuláře',
                'verbose_name_plural': 'Zprávy z formuláře',
                'ordering': ['-created_at'],
            },
        ),
    ]
